### ISSUE TITLE
which one is the best setting for ogb_molhiv dataset

### ISSUE THREAD

**Issue by lipingcoding** [lsj2408/GraphNorm#2]
there are two hyper parameter setting for ogb_molhiv, one is at the outer-most README, the other is at GraphNorm/GraphNorm_ws/ogbg_ws/scripts/Example-gcn-test-performance/seed-1-5-gcn_run.sh. I have tried both, but none of them can obtain reported result

**Comment by lsj2408** [comment]
Hi, the setting on README is for reproducing the OGB Leaderboard performance (the best one): https://ogb.stanford.edu/docs/leader_graphprop/ , while the Example-gcn-test-performance/ is for reproducing the performance on Table 1 in our paper. In our experimental setup, the performance is reproducible and we also provide the checkpoints for further verification: https://onedrive.live.com/?cid=c1d01e33b00b7206&id=C1D01E33B00B7206%21109&authkey=!AJO5a6g6esOcuoQ

**Comment by lipingcoding** [comment]
Thanks. I tried again. And obtained reported result.
